version: "3"
services:
  postgres-db:
    container_name: "shop-db_sql"
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_ROOT_USERNAME}
      - POSTGRES_PASSWORD=${DB_ROOT_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5435:5432
    expose:
      - "5435"
